MvcMusicStore/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Web.Mvc;
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Controllers
{
    
    public class ShoppingCartController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5

        public ActionResult AddToCart(int id)
        {

            // Retrieve the album from the database
            var addedAlbum = storeDB.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.Carts
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }
    }
}

MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers
{
  
    public class StoreController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /Store/

        public ActionResult Index()
        {
            var genres = storeDB.Genres.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco

        public ActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            var genreModel = storeDB.Genres.Include("Albums")
                .Single(g => g.Name == genre);

            return View(genreModel);
        }

        //
        // GET: /Store/Details/5

        public ActionResult Details(int id)
        {
            var album = storeDB.Albums.Find(id);

            return View(album);
        }

        //
        // GET: /Store/GenreMenu

        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.ToList();

            return PartialView(genres);
        }

    }
}

MvcMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" 
        type="text/javascript"></script>
    
    <link href="../../font-awesome/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    <div id="header">
        <h2><a href="/" title="Universal Music Group">

            @{
                string logoImage = null, theme = null;

                if (System.Threading.Thread.CurrentPrincipal.Identity != null && System.Threading.Thread.CurrentPrincipal.Identity.IsAuthenticated)
                {
                    var tenantSettings = HttpContext.Current.Items.Contains(CelloSaaS.Integration.Helpers.AppSettingHelpers.GetValue<string>(CelloSaaS.Integration.Helpers.AppSettingConstants.TenantSettingsKey))
                                            ? HttpContext.Current.Items[CelloSaaS.Integration.Helpers.AppSettingHelpers.GetValue<string>(CelloSaaS.Integration.Helpers.AppSettingConstants.TenantSettingsKey)] as Dictionary<string, string>
                                            : null;
                    var tenantDetails = HttpContext.Current.Items.Contains(CelloSaaS.Integration.Helpers.AppSettingHelpers.GetValue<string>(CelloSaaS.Integration.Helpers.AppSettingConstants.TenantDetails))
                                           ? HttpContext.Current.Items[CelloSaaS.Integration.Helpers.AppSettingHelpers.GetValue<string>(CelloSaaS.Integration.Helpers.AppSettingConstants.TenantDetails)] as Dictionary<string, string>
                                           : null;
                    if (tenantSettings != null && tenantSettings.Count > 0 && tenantSettings.ContainsKey("Logo"))
                    {
                        logoImage = tenantSettings["Logo"];
                    }
                    theme = tenantSettings.ContainsKey("Theme") ? tenantSettings["Theme"] as string : string.Empty;

                    if (!string.IsNullOrEmpty(theme))
                    {
                        theme = theme.ToLowerInvariant() + ".";
                    }
                }
                string adminAppUri = CelloSaaS.Integration.Helpers.AppSettingHelpers.GetValue<string>(CelloSaaS.Integration.Helpers.AppSettingConstants.AdminAppUri);
                string logoImagePath = adminAppUri + "LogoImageFolder/";
                logoImage = logoImage ?? (HttpContext.Current.Items.Contains("DefaultLogo") ? HttpContext.Current.Items["DefaultLogo"] as string : "cellosaas.svg");
                string logoFullPath = string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}{1}", logoImagePath, logoImage);

            }
            <link href="@Url.Content(string.Format("~/Content/{0}Site.css", theme))" rel="stylesheet"  type="text/css" />

            @Html.Raw("<img src='" + logoFullPath + "' alt='logo' />")
            <span>
                <br />
                Universal Music Group</span></a></h2>
        <ul id="navlist">
            @{
                
                switch(CelloSaaS.Integration.Helpers.MeteringHelper.MeteringAlert("Album"))
                {
                    case CelloSaaS.Integration.Helpers.MeteringHelper.MeteringAlertStatus.Normal:
                        break;
                        
                    case CelloSaaS.Integration.Helpers.MeteringHelper.MeteringAlertStatus.Error:
                        <li><a href="javascript:void();"><i style="color:red" class="fa fa-exclamation-circle">Album Limit Reached</i></a></li>
                        break;
                        
                    case CelloSaaS.Integration.Helpers.MeteringHelper.MeteringAlertStatus.Warning:
                        <li><a href="javascript:void();"><i style="color:#f0ad4e" class="fa fa-exclamation-triangle">
                            @{double balance=@CelloSaaS.Integration.Helpers.MeteringHelper.MeteringBalance("Album");
                              string album="Albums";
                              if (balance <= 1)
                              {
                                  album = "Album";
                              }
                              }
                              
                            @balance @album Only Remining</i></a></li>
                             
                        break;
                }
                if (System.Threading.Thread.CurrentPrincipal.Identity.IsAuthenticated)
                {
                <li><a href="javascript:void();"><span>Welcome : @User.Identity.Name</span></a></li>
                }                    
            }
            <li class="first"><a href="@Url.Content("~")" id="current">Home</a></li>
            @{
                   if (User.IsInRole("GR$Tenant_Admin"))
                    {
                <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
              
               
                <li><a href="@Url.Content("~/Store/")">Store</a></li>
                <li><a href="@Url.Content("~/StoreManager/")">Admin</a></li>
            }

                if (System.Threading.Thread.CurrentPrincipal.Identity.IsAuthenticated)
                {
                <li><a href="@Url.Action("LogOff", "Account")">LogOut</a></li>
                    if (User.IsInRole("GR$Tenant_Admin"))
                    {
                <li><a href="@adminAppUri">Setup</a></li>
                    }
                }
            }
        </ul>
    </div>

    @{  if (User.IsInRole("GR$Tenant_Admin"))
                    {
            Html.RenderAction("GenreMenu", "Store");
        }
    }

    <div id="main">
        @RenderBody()
    </div>

    <div id="footer">
        Powered by <a href="http://microgroove.com">MicroGroove</a>
    </div>
</body>
</html>

MvcMusicStore/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @{
        string theme = HttpContext.Current.Items.Contains("Theme") ? HttpContext.Current.Items["Theme"] as string : string.Empty;

        if (!string.IsNullOrEmpty(theme))
        {
            theme = theme.ToLowerInvariant() + ".";
        }
    }

    <link href="@Url.Content(string.Format("~/Content/{0}Site.css", theme))" rel="stylesheet"  type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" 
        type="text/javascript"></script>
</head>
<body>
    <div id="header">
        <h1><a href="/">ASP.NET MVC MUSIC STORE</a></h1>
        <ul id="navlist">
            <li class="first"><a href="@Url.Content("~")" id="current">Home</a></li>
            <li><a href="@Url.Content("~/Store/")">Store</a></li>
            <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
            <li><a href="@Url.Content("~/StoreManager/")">Admin</a></li>
        </ul>
    </div>

    @{Html.RenderAction("GenreMenu", "Store");}

    <div id="main">
        @RenderBody()
    </div>

    <div id="footer">
        built with <a href="http://asp.net/mvc">ASP.NET MVC 3</a>
    </div>
</body>
</html>